# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-26 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrev', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transformation_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[(1, b'Structure/Process'), (2, b'Strategy/Policy'), (3, b'Service Delivery')], max_length=20)),
                ('ministry', models.ManyToManyField(to='transformations.Ministry')),
            ],
        ),
    ]
