# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-28 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformations', '0002_auto_20170726_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformation',
            name='problem',
            field=models.TextField(null=True, verbose_name=b'What problem is it trying to solve?'),
        ),
        migrations.AddField(
            model_name='transformation',
            name='specific_orgs',
            field=models.CharField(max_length=240, null=True, verbose_name=b'Which specific or other organizations?'),
        ),
        migrations.AddField(
            model_name='transformation',
            name='status',
            field=models.CharField(blank=True, choices=[(1, b'Defining Direction'), (2, b'Design Stage'), (3, b'Implementation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='category',
            field=models.CharField(blank=True, choices=[(1, b'Structure/Process'), (2, b'Strategy/Policy'), (3, b'Service Delivery')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='description',
            field=models.TextField(verbose_name=b'High-Level Description'),
        ),
    ]
