# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-28 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformations', '0003_auto_20170728_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformation',
            name='primary_contact',
            field=models.CharField(max_length=100, null=True, verbose_name=b'Primary Contact'),
        ),
    ]
