# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-28 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformations', '0004_transformation_primary_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformation',
            name='category',
            field=models.CharField(blank=True, choices=[(b'structure', b'Structure/Process'), (b'strategy', b'Strategy/Policy'), (b'service', b'Service Delivery'), (b'people', b'People Development'), (b'all', b'All of the Above')], max_length=20),
        ),
    ]
