# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-28 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformations', '0005_auto_20170728_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformation',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='primary_contact',
            field=models.CharField(blank=True, default='n/a', max_length=100, verbose_name=b'Primary Contact'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transformation',
            name='problem',
            field=models.TextField(blank=True, default='n/a', verbose_name=b'What problem is it trying to solve?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transformation',
            name='specific_orgs',
            field=models.CharField(blank=True, default='n/a', max_length=240, verbose_name=b'Which specific or other organizations?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transformation',
            name='status',
            field=models.CharField(blank=True, choices=[(b'direction', b'Defining Direction'), (b'design', b'Design Stage'), (b'implementation', b'Implementation'), (b'sustainment', b'Sustainment'), (b'complete', b'Past Transformation')], max_length=20),
        ),
    ]
