# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-29 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('transformations', '0007_transformation_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name=b'Resource Title')),
                ('attachment', models.FileField(upload_to=b'')),
                ('link', models.URLField()),
                ('description', models.TextField()),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.AlterField(
            model_name='transformation',
            name='specific_orgs',
            field=models.CharField(blank=True, max_length=240, verbose_name=b'Which specific areas or other organizations are involved?'),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='title',
            field=models.CharField(max_length=100, verbose_name=b'Transformation Title'),
        ),
        migrations.AddField(
            model_name='resource',
            name='transformation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transformations.Transformation'),
        ),
    ]
