# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-01 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('transformations', '0008_auto_20170729_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=b'Give this resource a descriptive name.', max_length=50, verbose_name=b'Title')),
                ('description', models.TextField()),
                ('date_modified', models.DateTimeField()),
                ('resource', models.FileField(upload_to=b'', verbose_name=b'Attachment')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=b'Give this resource a descriptive name.', max_length=50, verbose_name=b'Title')),
                ('description', models.TextField()),
                ('date_modified', models.DateTimeField()),
                ('resource', models.URLField(verbose_name=b'Link')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='resource',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='transformation',
        ),
        migrations.AlterModelOptions(
            name='ministry',
            options={'ordering': ['abbrev']},
        ),
        migrations.AlterField(
            model_name='transformation',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.AddField(
            model_name='link',
            name='transformation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='transformations.Transformation'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='transformation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='transformations.Transformation'),
        ),
    ]
